name: Build gh-packages-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
      - run: npm pack
      - run: echo "ARTIFACT_NAME=$(cat .artifact-name)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: gh-packages-test
          path: ./{{ ARTIFACT_NAME }}
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: gh-packages-test
          path: .
      - run: ls -al