name: Build gh-packages-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*
          if-no-files-found: error
          retention-days: 1
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/download-artifact@v2
          with:
            name: dist
            path: dist/
        - name: Display structure of downloaded files
          run: ls -R
          working-directory: .
        - uses: actions/setup-node@v1
          with:
            node-version: 14
            registry-url: "https://npm.pkg.github.com"
            scope: "@voronin-de"
        - run: npm install
        - run: echo "registry=https://npm.pkg.github.com/@voronin-de" >> .npmrc
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}